services:
  major:
    build: .
    ports:
      - "${MAJOR_PORT}:8000"
    command: --test
    network_mode: host
    environment:
      PORT: 8000
      ADMIN_USER: ${MAJOR_ADMIN_USER}
      ADMIN_PASSWORD: ${MAJOR_ADMIN_PASSWORD}
